version: '3.3'

services:

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379"
    volumes:
      - redis_data:/data

  cerberus:
    container_name: cerberus
    environment:
      username: "${PCLOUD_USER}"
      password: "${PCLOUD_PASS}"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - /home/bruno:/home/bruno:ro

volumes:
    redis_data:
